import { useWorkbench } from "../../core/WorkbenchProvider.jsx";
import { Empty, Field, ModalForm, Status, splitComma } from "../../core/ui.jsx";

const slots = (plan) => plan.bank_slots || [];
const resumeCount = (plan) => plan.experience_question_ids?.length || 0;

export default function PlansPage() {
  const { API, data, request, reloadRoute, openModal, closeModal, toast } = useWorkbench();
  const done = async (message) => { await reloadRoute("roles", "plans", "questions", "candidates"); closeModal(); toast("操作完成", message); };
  const createRole = () => openModal({ title: "新建岗位要求", body: <ModalForm onSubmit={async (form) => { const positionId = form.get("job_position_id"); const item = await request(`${API}/job-positions/${positionId}/role-requirements`, { method: "POST", body: { title: form.get("title"), description: form.get("description"), must_have_skills: splitComma(form.get("must_have_skills")), nice_to_have_skills: splitComma(form.get("nice_to_have_skills")), seniority: form.get("seniority"), interview_duration_minutes: Number(form.get("interview_duration_minutes")) } }); await done(`${item.title} 已创建`); }}><Field label="归属岗位" full><select className="form-select" name="job_position_id">{data.positions.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="岗位名称" full><input className="form-input" name="title" required /></Field><Field label="级别"><select className="form-select" name="seniority" defaultValue="senior"><option value="junior">初级</option><option value="mid">中级</option><option value="senior">高级</option></select></Field><Field label="时长"><input className="form-input" name="interview_duration_minutes" type="number" defaultValue="45" /></Field><Field label="描述" full><textarea className="form-textarea" name="description" required /></Field><Field label="必备技能" full><input className="form-input" name="must_have_skills" required /></Field><Field label="加分技能" full><input className="form-input" name="nice_to_have_skills" /></Field></ModalForm> });
  const generate = () => openModal({ title: "生成面试计划", body: <ModalForm submitLabel="生成并启用计划" onSubmit={async (form) => { const role = data.roles.find((item) => item.id === form.get("role_requirement_id")); const kb = data.knowledgeBases.find((item) => item.id === form.get("knowledge_base_id")); const position = data.positions.find((item) => item.id === role?.job_position_id); const assigned = kb && (kb.job_position_id === role?.job_position_id || position?.knowledge_base_ids?.includes(kb.id)); if (!role || !assigned) throw new Error("请先在招聘流程中为岗位选择该题库"); const plan = await request(`${API}/interview-plans/generate`, { method: "POST", body: { role_requirement_id: role.id, job_position_id: role.job_position_id, candidate_profile_id: form.get("candidate_profile_id"), knowledge_base_ids: [kb.id], question_count: Number(form.get("question_count")), approve: true, strategy: { coverage: splitComma(form.get("coverage")), allow_followups: true, max_same_skill_questions: 3, difficulty_curve: true } } }); await done(`计划已启用，包含 ${slots(plan).length} 道岗位题和 ${resumeCount(plan)} 道简历题。${plan.assembly_summary?.warnings?.join("；") || "可直接创建预约"}`); }}><p className="form-hint">点击生成即表示确认当前岗位、候选人、题库和策略；系统通过就绪校验后会直接启用，无需再次审批。自动选择本岗位最新合格简历中最多3道已批准问题，放在岗位题后；候选人确认预约后才生成简历读题语音，未就绪题目在面试末尾跳过。</p><Field label="岗位要求" full><select className="form-select" name="role_requirement_id">{data.roles.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="候选人" full><select className="form-select" name="candidate_profile_id">{data.candidates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="岗位题库" full><select className="form-select" name="knowledge_base_id">{data.knowledgeBases.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="岗位题数量"><input className="form-input" name="question_count" type="number" min="1" defaultValue="6" /></Field><Field label="覆盖技能"><input className="form-input" name="coverage" /></Field></ModalForm> });
  return <><section className="page-header"><div><h1>面试计划</h1><p>{data.plans.length} 份候选人专属计划</p></div><div className="page-actions"><button className="button button-secondary" onClick={createRole}>新建岗位要求</button><button className="button button-primary" onClick={generate} disabled={!data.roles.length || !data.questions.length || !data.candidates.length}>生成计划</button></div></section><div className="two-column"><section><h2>计划列表</h2>{data.plans.length ? data.plans.map((plan) => <article className="plan-card" key={plan.id}><div className="question-card-top"><strong>{data.roles.find((item) => item.id === plan.role_requirement_id)?.title || plan.id}</strong><Status value={plan.status} /></div><p>{slots(plan).length} 道岗位题 · {resumeCount(plan)} 道简历题（最后提问）</p>{resumeCount(plan) < 2 && <p className="form-hint">本计划简历题不足2道，请在招聘流程中批准简历问题后重新生成计划。</p>}{plan.status === "draft" && <p className="form-hint">历史草稿：可通过 API 完成审核，或重新生成一份可直接使用的计划。</p>}</article>) : <Empty title="暂无计划" copy="生成候选人专属计划" />}</section><section><h2>岗位要求</h2>{data.roles.length ? data.roles.map((role) => <article className="list-card" key={role.id}><strong>{role.title}</strong><span>{role.must_have_skills?.join(" · ")}</span></article>) : <Empty title="暂无岗位要求" copy="先创建岗位画像" />}</section></div></>;
}
