import { useEffect, useMemo, useRef, useState } from "react";
import { createCandidateInterviewRuntime } from "../../../candidate/runtime.js";
import { createPcm16kStream } from "../../../candidate/pcm-stream.js";
import { useWorkbench } from "../../core/WorkbenchProvider.jsx";
import { Empty, Field, Status } from "../../core/ui.jsx";

export default function CandidateFeaturePage() {
  const { route } = useWorkbench();
  return route.view === "invite" ? <InvitationPage /> : <CandidateRoom />;
}

function InvitationPage() {
  const { API, data, request, toast } = useWorkbench(); const [busy, setBusy] = useState(false); const [entering, setEntering] = useState(false); const invitation = data.invitation; const [confirmed, setConfirmed] = useState(invitation?.status === "registered"); const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 30000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (invitation?.status === "registered") setConfirmed(true); }, [invitation?.status]);
  if (!invitation) return <PublicShell><Empty title="邀请链接不可用" copy="链接可能已过期、已使用或被撤销" /></PublicShell>;
  const token = invitation.token || location.hash.split("/")[1]; const startAt = new Date(invitation.scheduled_start_at); const endAt = new Date(invitation.scheduled_end_at); const canEnter = now >= startAt.getTime() && now <= endAt.getTime();
  const confirm = async (event) => { event.preventDefault(); setBusy(true); try { const form = new FormData(event.currentTarget); await request(`${API}/public/interview-invitations/${encodeURIComponent(token)}/intake`, { method: "POST", body: { name: form.get("name"), email: form.get("email"), phone: form.get("phone"), consent: { accepted: form.get("privacy_accepted") === "on", version: invitation.consent?.version || "v1", recording_accepted: form.get("recording_accepted") === "on" } } }); setConfirmed(true); toast("预约确认成功", "系统已安排面试前 30 分钟邮件提醒"); } catch (error) { toast("暂时无法确认预约", error.message, "error"); } finally { setBusy(false); } };
  const enterInterview = async () => { setEntering(true); try { let granted = false; let stream; try { stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }); granted = stream.getAudioTracks().length > 0; } finally { stream?.getTracks().forEach((track) => track.stop()); } const readiness = await request(`${API}/public/interview-invitations/${encodeURIComponent(token)}/readiness`, { method: "POST", body: { browser_supported: Boolean(navigator.mediaDevices && window.MediaRecorder), microphone_granted: granted, audio_content_type: supportedMimeType() } }); if (!readiness.can_start) throw new Error("麦克风或预约运行条件尚未就绪"); const result = await request(`${API}/public/interview-invitations/${encodeURIComponent(token)}/start`, { method: "POST" }); location.href = result.candidate_join_url; } catch (error) { toast("暂时无法进入面试", error.message, "error"); setEntering(false); } };
  return <PublicShell><section className="panel candidate-invitation" style={{ maxWidth: 760, margin: "48px auto", padding: 28 }}><p className="eyebrow">候选人面试预约</p><h1>{invitation.position_name}</h1><div className="appointment-time-card"><span>预约时间</span><strong>{formatAppointmentTime(startAt)} — {formatAppointmentTime(endAt)}</strong></div>{confirmed ? <div className="appointment-confirmed"><Status value="预约已确认" tone="ready" /><h2>身份核验通过</h2><p>我们会在面试开始前 30 分钟向您的登记邮箱发送提醒。请保留当前邀请链接，到预约时间后再进入面试。</p><button className="button button-primary" type="button" disabled={!canEnter || entering} onClick={enterInterview}>{entering ? "正在检查设备…" : canEnter ? "检查设备并进入面试" : "尚未到面试时间"}</button></div> : <><p>{invitation.consent?.privacy_notice}</p><p className="form-hint">核验通过后即确认预约，不会立即启动面试。</p><form onSubmit={confirm}><div className="form-grid"><Field label="姓名" full><input className="form-input" name="name" required /></Field><Field label="邮箱"><input className="form-input" name="email" type="email" required /></Field><Field label="手机号"><input className="form-input" name="phone" required /></Field></div><label><input type="checkbox" name="privacy_accepted" required /> 我已阅读并同意隐私说明</label>{invitation.consent?.recording_required && <label style={{ display: "block", marginTop: 12 }}><input type="checkbox" name="recording_accepted" required /> 我同意录制答题音频用于转写、评分与复核</label>}<button className="button button-primary" type="submit" disabled={busy} style={{ marginTop: 24 }}>{busy ? "正在核验…" : "核验身份并确认预约"}</button></form></>}</section></PublicShell>;
}

function CandidateRoom() {
  const wb = useWorkbench(); const { API, data, route, request, setResource, toast } = wb; const interview = data.selectedInterview; const token = data.candidateToken || route.candidateToken;
  const [stream, setStream] = useState(null); const [devices, setDevices] = useState({ audio: [], video: [] }); const [selectedAudio, setSelectedAudio] = useState(""); const [selectedVideo, setSelectedVideo] = useState(""); const [avatarMedia, setAvatarMedia] = useState(null); const [phase, setPhase] = useState("idle"); const [audioUri, setAudioUri] = useState(null); const [mimeType, setMimeType] = useState("audio/webm"); const [transcript, setTranscript] = useState(""); const [interim, setInterim] = useState(""); const [duration, setDuration] = useState(0); const [audioEnabled, setAudioEnabled] = useState(true); const [videoEnabled, setVideoEnabled] = useState(true); const videoRef = useRef(null); const streamRef = useRef(null); const socketRef = useRef(null); const sttSocketRef = useRef(null); const pcmRef = useRef(null); const timerRef = useRef(null); const recognitionRef = useRef(null); const avatarRef = useRef(null); const startedAtRef = useRef(0);
  const candidateRequest = (suffix = "", options = {}) => request(`${API}/public/interviews/${encodeURIComponent(interview?.id || route.selectedInterviewId)}${suffix}`, { ...options, headers: { ...(options.headers || {}), "X-Candidate-Session-Token": token || "" } });
  const runtime = useMemo(() => createCandidateInterviewRuntime({ onStateChange: (state) => { setPhase(state.phase); if (state.mimeType) setMimeType(state.mimeType); }, onRecoveryNeeded: (message) => toast("录音等待恢复", message, "error") }), []);
  const refreshInterview = async () => setResource("selectedInterview", await candidateRequest());
  const ensureSocket = async () => { if (socketRef.current?.readyState === WebSocket.OPEN) return socketRef.current; return new Promise((resolve, reject) => { const protocol = location.protocol === "https:" ? "wss:" : "ws:"; const socket = new WebSocket(`${protocol}//${location.host}${API}/interviews/${encodeURIComponent(interview.id)}/live?role=candidate&token=${encodeURIComponent(token)}`); socketRef.current = socket; socket.addEventListener("open", () => { socket.send(JSON.stringify({ type: "session.ready", payload: { source: "react_candidate" } })); resolve(socket); }, { once: true }); socket.addEventListener("message", async ({ data: raw }) => { const event = JSON.parse(raw); if (event.type === "media.recording.stopped") { runtime.acknowledgeMediaStored(); setAudioUri(event.payload.audio_uri); setMimeType(event.payload.mime_type || "audio/webm"); } if (event.type === "stt.transcript.partial") setInterim(event.payload.text || ""); if (["evaluation.completed", "interview.completed"].includes(event.type)) { setTranscript(""); setInterim(""); setAudioUri(null); runtime.reset(); await refreshInterview(); } if (event.type === "error") toast("实时会话错误", event.payload?.message || event.payload?.code, "error"); }); socket.addEventListener("error", () => reject(new Error("实时会话连接失败")), { once: true }); socket.addEventListener("close", () => { if (phase === "recording") toast("实时连接中断", "录音保存在本地，可恢复提交", "error"); }); }); };
  const openSttStream = async () => new Promise((resolve, reject) => { const protocol = location.protocol === "https:" ? "wss:" : "ws:"; const socket = new WebSocket(`${protocol}//${location.host}${API}/interviews/${encodeURIComponent(interview.id)}/stt-stream?token=${encodeURIComponent(token)}`); socket.binaryType = "arraybuffer"; sttSocketRef.current = socket; let ready = false; socket.addEventListener("open", () => socket.send(JSON.stringify({ type: "stream.open", payload: { turn_id: current.id, content_type: "audio/pcm", sample_rate_hz: 16000, channels: 1, language: "zh-CN", enable_partial: true } }))); socket.addEventListener("message", async ({ data: raw }) => { const event = JSON.parse(raw); if (event.type === "stream.ready") { ready = true; resolve(socket); } else if (event.type === "transcript.partial") setInterim(event.text || ""); else if (event.type === "transcript.final") { setTranscript(event.text || ""); setInterim(""); } else if (event.type === "evaluation.completed") { setPhase("idle"); clearInterval(timerRef.current); await refreshInterview(); toast("回答已完成处理", "实时转写和评分已完成，结果等待企业复核"); } else if (event.type === "stream.error") { const error = new Error(event.message || event.error_code || "实时转写失败"); if (!ready) reject(error); else toast("实时转写失败", error.message, "error"); } }); socket.addEventListener("error", () => { if (!ready) reject(new Error("实时转写通道连接失败")); }, { once: true }); socket.addEventListener("close", () => { sttSocketRef.current = null; }); });
  useEffect(() => { if (videoRef.current) videoRef.current.srcObject = stream; }, [stream]);
  useEffect(() => () => { streamRef.current?.getTracks().forEach((track) => track.stop()); socketRef.current?.close(); sttSocketRef.current?.close(); pcmRef.current?.stop?.(); runtime.reset(); clearInterval(timerRef.current); recognitionRef.current?.stop?.(); closeAvatarSession(avatarRef.current, API, interview?.id || route.selectedInterviewId, token); }, [runtime]);
  if (!interview) return <PublicShell><Empty title="面试链接不可用" copy="请联系面试官重新发送链接" /></PublicShell>;
  const current = interview.turns?.find((item) => item.id === interview.current_turn_id); const completed = interview.turns?.filter((item) => item.status === "completed").length || 0; const finished = ["completed", "report_ready"].includes(interview.status);
  const openMedia = async (audioId = "", videoId = "") => { const next = await navigator.mediaDevices.getUserMedia({ audio: { ...(audioId ? { deviceId: { exact: audioId } } : {}), echoCancellation: true, noiseSuppression: true }, video: { ...(videoId ? { deviceId: { exact: videoId } } : {}), width: { ideal: 1280 }, height: { ideal: 720 } } }); streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = next; setStream(next); setAudioEnabled(true); setVideoEnabled(true); return next; };
  const enableMedia = async () => { try { const next = await openMedia(); const all = await navigator.mediaDevices.enumerateDevices(); const audio = all.filter((item) => item.kind === "audioinput"); const video = all.filter((item) => item.kind === "videoinput"); setDevices({ audio, video }); setSelectedAudio(next.getAudioTracks()[0]?.getSettings().deviceId || audio[0]?.deviceId || ""); setSelectedVideo(next.getVideoTracks()[0]?.getSettings().deviceId || video[0]?.deviceId || ""); await ensureSocket(); toast("设备已就绪", "麦克风和摄像头检查通过"); } catch (error) { toast("无法启用设备", error.message, "error"); } };
  const switchDevice = async (kind, deviceId) => { const audioId = kind === "audio" ? deviceId : selectedAudio; const videoId = kind === "video" ? deviceId : selectedVideo; try { await openMedia(audioId, videoId); if (kind === "audio") setSelectedAudio(deviceId); else setSelectedVideo(deviceId); toast("设备已切换", kind === "audio" ? "麦克风已更新" : "摄像头已更新"); } catch (error) { toast("设备切换失败", error.message, "error"); } };
  const toggleAudio = () => { const next = !audioEnabled; stream?.getAudioTracks().forEach((track) => { track.enabled = next; }); setAudioEnabled(next); };
  const toggleVideo = () => { const next = !videoEnabled; stream?.getVideoTracks().forEach((track) => { track.enabled = next; }); setVideoEnabled(next); };
  const startRecording = async () => { setAudioUri(null); setTranscript(""); setInterim(""); try { const sttSocket = await openSttStream(); pcmRef.current = await createPcm16kStream(stream, (chunk) => { if (sttSocket.readyState === WebSocket.OPEN) sttSocket.send(chunk); }); startedAtRef.current = Date.now(); setPhase("recording"); timerRef.current = setInterval(() => setDuration(Math.floor((Date.now() - startedAtRef.current) / 1000)), 1000); } catch (streamError) { try { const socket = await ensureSocket(); runtime.start({ mediaStream: stream, candidateSocket: socket, activeTurnId: current.id }); const started = Date.now(); timerRef.current = setInterval(() => setDuration(Math.floor((Date.now() - started) / 1000)), 1000); startRecognition(setTranscript, setInterim, recognitionRef); toast("实时转写已降级", "当前使用完整录音后批量转写"); } catch (error) { toast("无法开始录音", `${streamError.message}；${error.message}`, "error"); } } };
  const stopRecording = async () => { clearInterval(timerRef.current); recognitionRef.current?.stop?.(); if (pcmRef.current) { await pcmRef.current.stop(); pcmRef.current = null; setPhase("awaiting_server"); const elapsed = Math.max(1, Math.floor((Date.now() - startedAtRef.current) / 1000)); sttSocketRef.current?.send(JSON.stringify({ type: "stream.finish", payload: { duration_seconds: elapsed } })); } else runtime.stop(); };
  const recover = async () => { try { await runtime.recover(await ensureSocket()); } catch (error) { toast("恢复失败", error.message, "error"); } };
  const submitAnswer = async () => { try { await candidateRequest("/audio-answers", { method: "POST", body: { turn_id: current.id, audio_uri: audioUri, content_type: mimeType, language: "zh-CN", duration_seconds: duration, ...(["localhost", "127.0.0.1"].includes(location.hostname) && transcript ? { development_transcript: transcript, development_confidence: .85 } : {}) } }); setAudioUri(null); runtime.reset(); await refreshInterview(); toast("回答已完成处理", "结果将由企业面试官复核"); } catch (error) { toast("回答提交失败", error.message, "error"); } };
  const speak = async () => { try { await closeAvatarSession(avatarRef.current, API, interview.id, token); avatarRef.current = null; setAvatarMedia(null); const response = await candidateRequest("/avatar/speak", { method: "POST", body: { turn_id: current.id, language: "zh-CN", voice: "default" } }); if (["video", "webrtc"].includes(response.mode) && response.stream_url) { avatarRef.current = response; setAvatarMedia(response); } else if (response.mode === "audio" && response.audio_uri) await new Audio(response.audio_uri).play(); else if (speechSynthesis) { speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(response.text); utterance.lang = "zh-CN"; speechSynthesis.speak(utterance); } } catch (error) { toast("数字人读题失败", error.message, "error"); } };
  return <PublicShell><div className="candidate-room">{finished ? <section className="candidate-completion"><h1>面试已完成</h1><p>回答已经提交，报告将由企业人员审核。</p></section> : <><section className="candidate-stage-grid"><div className="candidate-avatar-stage">{avatarMedia?.mode === "webrtc" ? <iframe title="实时数智人" allow="autoplay; fullscreen" src={`/web/webrtc-player.html?url=${encodeURIComponent(avatarMedia.stream_url)}`} /> : avatarMedia?.mode === "video" ? <video src={avatarMedia.stream_url} autoPlay playsInline onEnded={() => setAvatarMedia(null)} /> : <img src="/web/assets/digital-interviewer.png" alt="数字人面试官" />}<button className="button button-secondary" onClick={speak} disabled={!current}>重新朗读</button></div><aside className="candidate-device-panel"><div className="candidate-camera"><video ref={videoRef} autoPlay muted playsInline />{!stream && <button className="button button-primary" onClick={enableMedia}>检查设备</button>}</div>{stream && <><div className="device-controls"><button className="device-toggle" onClick={toggleAudio}>{audioEnabled ? "麦克风开" : "麦克风关"}</button><button className="device-toggle" onClick={toggleVideo}>{videoEnabled ? "摄像头开" : "摄像头关"}</button></div><Field label="麦克风"><select className="form-select" value={selectedAudio} onChange={(event) => switchDevice("audio", event.target.value)}>{devices.audio.map((item, index) => <option key={item.deviceId} value={item.deviceId}>{item.label || `麦克风 ${index + 1}`}</option>)}</select></Field><Field label="摄像头"><select className="form-select" value={selectedVideo} onChange={(event) => switchDevice("video", event.target.value)}>{devices.video.map((item, index) => <option key={item.deviceId} value={item.deviceId}>{item.label || `摄像头 ${index + 1}`}</option>)}</select></Field></>}</aside></section><section className="candidate-question-band"><div className="candidate-question-head"><div><span>第 {current?.order || "-"} / {interview.turns?.length} 题</span><h1>{current?.question_spoken_text || "等待下一题"}</h1></div><span>{completed}/{interview.turns?.length}</span></div><textarea className="form-textarea" value={`${transcript}${interim ? ` ${interim}` : ""}`} readOnly placeholder="服务端转写为最终答案" /><div className="candidate-answer-actions"><button className="button button-record" onClick={startRecording} disabled={!stream || !current || !["idle", "stored"].includes(phase)}>开始回答</button><button className="button button-secondary" onClick={stopRecording} disabled={phase !== "recording"}>结束录音</button>{phase === "recoverable" && <button className="button button-secondary" onClick={recover}>恢复提交录音</button>}<button className="button button-primary" onClick={submitAnswer} disabled={!audioUri || ["recording", "stopping", "replaying"].includes(phase)}>提交录音</button></div></section></>}</div></PublicShell>;
}

function PublicShell({ children }) { return <div className="candidate-room"><header className="candidate-header"><span className="candidate-brand"><strong>Interviewer</strong><small>智能面试</small></span></header>{children}</div>; }
function supportedMimeType() { return ["audio/webm;codecs=opus", "audio/webm", "audio/mp4", "audio/ogg;codecs=opus"].find((value) => window.MediaRecorder?.isTypeSupported?.(value)) || "audio/webm"; }
function formatAppointmentTime(value) { return Number.isNaN(value.getTime()) ? "待确认" : value.toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }); }
function startRecognition(setTranscript, setInterim, ref) { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) return; const instance = new Recognition(); instance.lang = "zh-CN"; instance.continuous = true; instance.interimResults = true; instance.addEventListener("result", (event) => { let final = ""; let partial = ""; for (let index = event.resultIndex; index < event.results.length; index += 1) { if (event.results[index].isFinal) final += event.results[index][0].transcript; else partial += event.results[index][0].transcript; } if (final) setTranscript((value) => `${value} ${final}`.trim()); setInterim(partial); }); ref.current = instance; instance.start(); }
function closeAvatarSession(media, API, interviewId, token) { if (!media?.session_id || !interviewId) return Promise.resolve(); return fetch(`${API}/public/interviews/${encodeURIComponent(interviewId)}/avatar/session/close`, { method: "POST", keepalive: true, headers: { "Content-Type": "application/json", "X-Candidate-Session-Token": token || "" }, body: JSON.stringify({ session_id: media.session_id }) }).catch(() => {}); }
