"""Generate and statically inspect a production shell environment file.

The public interface deliberately keeps secret creation, safe file permissions,
and validation behind two functions. Neither function contacts dependencies.
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import shlex
import stat
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Mapping, Optional, Sequence, Tuple
from urllib.parse import urlparse

from cryptography.fernet import Fernet


DEFAULT_PATH = Path(".env.production.local")
_SECURITY_NAMES = (
    "INTERVIEWER_API_TOKENS_JSON",
    "INTERVIEWER_CONTACT_ENCRYPTION_KEY",
    "INTERVIEWER_CONTACT_LOOKUP_SECRET",
    "INTERVIEWER_PROVIDER_SECRET_ENCRYPTION_KEY",
    "INTERVIEWER_CANDIDATE_TOKEN_SECRET",
    "INTERVIEWER_WEBSOCKET_TICKET_SECRET",
    "INTERVIEWER_FILE_SIGNING_SECRET",
    "INTERVIEWER_MEDIA_SIGNING_SECRET",
)


@dataclass(frozen=True)
class ProductionConfigReport:
    path: Path
    valid: bool
    configured: Tuple[str, ...]
    missing: Tuple[str, ...]
    invalid: Tuple[str, ...]


def generate_production_config(
    path: Path,
    *,
    postgres_dsn: str,
    redis_url: str,
    organization_id: str = "org_default",
    clamd_host: str = "",
    clamd_port: int = 3310,
    oss_endpoint: str = "",
    oss_bucket: str = "",
    oss_access_key_id: str = "",
    oss_access_key_secret: str = "",
) -> ProductionConfigReport:
    """Atomically create a 0600 shell-sourceable config without overwriting."""
    resolved = path.expanduser().resolve()
    values = _generated_values(
        postgres_dsn=postgres_dsn,
        redis_url=redis_url,
        organization_id=organization_id,
        clamd_host=clamd_host,
        clamd_port=clamd_port,
        oss_endpoint=oss_endpoint,
        oss_bucket=oss_bucket,
        oss_access_key_id=oss_access_key_id,
        oss_access_key_secret=oss_access_key_secret,
    )
    resolved.parent.mkdir(parents=True, exist_ok=True)
    descriptor = os.open(resolved, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write("# Generated by python -m app.operations.production_config init\n")
            handle.write("# Load with: set -a; source .env.production.local; set +a\n")
            for name, value in values.items():
                handle.write("%s=%s\n" % (name, shlex.quote(value)))
    except BaseException:
        try:
            resolved.unlink()
        except FileNotFoundError:
            pass
        raise
    os.chmod(resolved, stat.S_IRUSR | stat.S_IWUSR)
    return inspect_production_config(resolved)


def inspect_production_config(path: Path) -> ProductionConfigReport:
    """Validate required deployment fields without exporting or printing values."""
    resolved = path.expanduser().resolve()
    values = _parse_shell_environment(resolved)
    missing = []
    invalid = []

    required = (
        "INTERVIEWER_RUNTIME_ENV",
        "INTERVIEWER_ORGANIZATION_ID",
        "INTERVIEWER_DB_BACKEND",
        "INTERVIEWER_POSTGRES_DSN",
        "INTERVIEWER_REDIS_URL",
        *_SECURITY_NAMES,
        "INTERVIEWER_FILE_STORAGE_BACKEND",
        "INTERVIEWER_MEDIA_RECORDING_BACKEND",
        "INTERVIEWER_OSS_ENDPOINT",
        "INTERVIEWER_OSS_BUCKET",
        "INTERVIEWER_OSS_ACCESS_KEY_ID",
        "INTERVIEWER_OSS_ACCESS_KEY_SECRET",
    )
    for name in required:
        if not values.get(name, "").strip():
            missing.append(name)

    scanner_ready = bool(
        values.get("INTERVIEWER_FILE_SCANNER_COMMAND", "").strip()
        or values.get("INTERVIEWER_FILE_SCANNER_CLAMD_HOST", "").strip()
    )
    if not scanner_ready:
        missing.append("INTERVIEWER_FILE_SCANNER_COMMAND|INTERVIEWER_FILE_SCANNER_CLAMD_HOST")

    if values.get("INTERVIEWER_RUNTIME_ENV") not in {None, "", "production"}:
        invalid.append("INTERVIEWER_RUNTIME_ENV")
    if values.get("INTERVIEWER_DB_BACKEND") not in {None, "", "postgresql", "postgres"}:
        invalid.append("INTERVIEWER_DB_BACKEND")
    if values.get("INTERVIEWER_FILE_STORAGE_BACKEND") not in {None, "", "aliyun", "aliyun_oss", "oss"}:
        invalid.append("INTERVIEWER_FILE_STORAGE_BACKEND")
    if values.get("INTERVIEWER_MEDIA_RECORDING_BACKEND") not in {None, "", "private", "file_storage"}:
        invalid.append("INTERVIEWER_MEDIA_RECORDING_BACKEND")
    for name in ("INTERVIEWER_POSTGRES_DSN", "INTERVIEWER_REDIS_URL", "INTERVIEWER_OSS_ENDPOINT"):
        value = values.get(name, "").strip()
        if value and not urlparse(value).scheme:
            invalid.append(name)
    if values.get("INTERVIEWER_FILE_SCANNER_CLAMD_PORT"):
        try:
            port = int(values["INTERVIEWER_FILE_SCANNER_CLAMD_PORT"])
            if port < 1 or port > 65535:
                raise ValueError
        except ValueError:
            invalid.append("INTERVIEWER_FILE_SCANNER_CLAMD_PORT")
    if not security_configuration_ready(values):
        invalid.append("production_security_configuration")

    missing_result = tuple(sorted(set(missing)))
    invalid_result = tuple(sorted(set(invalid)))
    return ProductionConfigReport(
        path=resolved,
        valid=not missing_result and not invalid_result,
        configured=tuple(sorted(name for name, value in values.items() if value)),
        missing=missing_result,
        invalid=invalid_result,
    )


def security_configuration_ready(values: Optional[Mapping[str, str]] = None) -> bool:
    """Return whether the production authentication/encryption subset is valid."""
    source: Mapping[str, str] = values if values is not None else os.environ
    try:
        tokens = json.loads(source.get("INTERVIEWER_API_TOKENS_JSON", "{}"))
    except json.JSONDecodeError:
        return False
    organization_id = source.get("INTERVIEWER_ORGANIZATION_ID", "org_default")
    token_values_ready = bool(
        isinstance(tokens, dict)
        and tokens
        and all(
            isinstance(value, dict)
            and value.get("organization_id") == organization_id
            and isinstance(value.get("roles"), list)
            and bool(value.get("roles"))
            for value in tokens.values()
        )
    )
    candidate_secret = source.get("INTERVIEWER_CANDIDATE_TOKEN_SECRET", "")
    websocket_secret = source.get("INTERVIEWER_WEBSOCKET_TICKET_SECRET", "") or candidate_secret
    media_secret = source.get("INTERVIEWER_MEDIA_SIGNING_SECRET", "") or source.get(
        "INTERVIEWER_FILE_SIGNING_SECRET", ""
    )
    return bool(
        token_values_ready
        and _valid_fernet(source.get("INTERVIEWER_CONTACT_ENCRYPTION_KEY", ""))
        and len(source.get("INTERVIEWER_CONTACT_LOOKUP_SECRET", "")) >= 32
        and _valid_fernet(source.get("INTERVIEWER_PROVIDER_SECRET_ENCRYPTION_KEY", ""))
        and len(candidate_secret) >= 32
        and len(websocket_secret) >= 32
        and len(source.get("INTERVIEWER_FILE_SIGNING_SECRET", "")) >= 32
        and len(media_secret) >= 32
    )


def _generated_values(**options: object) -> Dict[str, str]:
    organization_id = str(options["organization_id"])
    role_tokens = {
        secrets.token_urlsafe(32): {
            "actor_id": "production_admin",
            "organization_id": organization_id,
            "roles": ["admin"],
        },
        secrets.token_urlsafe(32): {
            "actor_id": "production_interviewer",
            "organization_id": organization_id,
            "roles": ["interviewer"],
        },
        secrets.token_urlsafe(32): {
            "actor_id": "production_reviewer",
            "organization_id": organization_id,
            "roles": ["reviewer"],
        },
    }
    values = {
        "INTERVIEWER_RUNTIME_ENV": "production",
        "INTERVIEWER_ORGANIZATION_ID": organization_id,
        "INTERVIEWER_DB_BACKEND": "postgresql",
        "INTERVIEWER_POSTGRES_DSN": str(options["postgres_dsn"]),
        "INTERVIEWER_REDIS_URL": str(options["redis_url"]),
        "INTERVIEWER_API_TOKENS_JSON": json.dumps(role_tokens, separators=(",", ":")),
        "INTERVIEWER_CONTACT_ENCRYPTION_KEY": Fernet.generate_key().decode("ascii"),
        "INTERVIEWER_CONTACT_LOOKUP_SECRET": secrets.token_urlsafe(48),
        "INTERVIEWER_PROVIDER_SECRET_ENCRYPTION_KEY": Fernet.generate_key().decode("ascii"),
        "INTERVIEWER_CANDIDATE_TOKEN_SECRET": secrets.token_urlsafe(48),
        "INTERVIEWER_WEBSOCKET_TICKET_SECRET": secrets.token_urlsafe(48),
        "INTERVIEWER_FILE_SIGNING_SECRET": secrets.token_urlsafe(48),
        "INTERVIEWER_MEDIA_SIGNING_SECRET": secrets.token_urlsafe(48),
        "INTERVIEWER_FILE_STORAGE_BACKEND": "aliyun_oss",
        "INTERVIEWER_MEDIA_RECORDING_BACKEND": "private",
        "INTERVIEWER_OSS_ENDPOINT": str(options["oss_endpoint"]),
        "INTERVIEWER_OSS_BUCKET": str(options["oss_bucket"]),
        "INTERVIEWER_OSS_ACCESS_KEY_ID": str(options["oss_access_key_id"]),
        "INTERVIEWER_OSS_ACCESS_KEY_SECRET": str(options["oss_access_key_secret"]),
        "INTERVIEWER_OSS_SSE": "AES256",
        "INTERVIEWER_FILE_SCANNER_CLAMD_HOST": str(options["clamd_host"]),
        "INTERVIEWER_FILE_SCANNER_CLAMD_PORT": str(options["clamd_port"]),
    }
    return values


def _valid_fernet(value: str) -> bool:
    if not value:
        return False
    try:
        Fernet(value.encode("ascii"))
        return True
    except (ValueError, UnicodeError):
        return False


def _parse_shell_environment(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            parts = shlex.split(line, comments=True, posix=True)
        except ValueError as exc:
            raise ValueError("Invalid shell syntax on line %d." % line_number) from exc
        if len(parts) != 1 or "=" not in parts[0]:
            raise ValueError("Expected one NAME=value assignment on line %d." % line_number)
        name, value = parts[0].split("=", 1)
        if not name.startswith("INTERVIEWER_") or not name.replace("_", "").isalnum():
            raise ValueError("Invalid environment name on line %d." % line_number)
        values[name] = value
    return values


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate or inspect an Interviewer production environment file.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    init = subparsers.add_parser("init", help="Create a new secret-bearing 0600 config file.")
    init.add_argument("--output", type=Path, default=DEFAULT_PATH)
    init.add_argument("--postgres-dsn", required=True)
    init.add_argument("--redis-url", required=True)
    init.add_argument("--organization-id", default="org_default")
    init.add_argument("--clamd-host", default="")
    init.add_argument("--clamd-port", type=int, default=3310)
    init.add_argument("--oss-endpoint", default="")
    init.add_argument("--oss-bucket", default="")
    init.add_argument("--oss-access-key-id", default="")
    init.add_argument("--oss-access-key-secret", default="")
    check = subparsers.add_parser("check", help="Statically check names and formats without exporting values.")
    check.add_argument("--input", type=Path, default=DEFAULT_PATH)
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command == "init":
            report = generate_production_config(
                args.output,
                postgres_dsn=args.postgres_dsn,
                redis_url=args.redis_url,
                organization_id=args.organization_id,
                clamd_host=args.clamd_host,
                clamd_port=args.clamd_port,
                oss_endpoint=args.oss_endpoint,
                oss_bucket=args.oss_bucket,
                oss_access_key_id=args.oss_access_key_id,
                oss_access_key_secret=args.oss_access_key_secret,
            )
            print("Created production config: %s" % report.path)
        else:
            report = inspect_production_config(args.input)
    except FileExistsError:
        print("Refusing to overwrite an existing config file.")
        return 2
    except (OSError, ValueError) as exc:
        print("Production config error: %s" % exc)
        return 2
    print("Configured variables: %d" % len(report.configured))
    print("Missing variables: %s" % (", ".join(report.missing) if report.missing else "none"))
    print("Invalid groups: %s" % (", ".join(report.invalid) if report.invalid else "none"))
    return 0 if report.valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
